"""
mib_object.py — IMibObject → Protocol.

Protocol for MIB object elements
"""

from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class IMibObject(Protocol):
    """Protocol defining MIB object interface."""

    def get_oid(self) -> str: ...
    def get_complete_oid(self) -> str: ...
    def get_oid_leaf(self) -> int: ...
    def get_parent_node_oid(self) -> str: ...
    def get_vendor_enterprise_oid(self) -> Optional[str]: ...
    def get_object_name(self) -> str: ...
    def get_full_name(self) -> str: ...
    def get_module_name(self) -> str: ...
    def get_module_version(self) -> str: ...
    def get_description(self) -> str: ...
    def get_reference(self) -> Optional[str]: ...
    def get_syntax(self) -> Optional[str]: ...
    def get_index(self) -> Optional[str]: ...
    def get_defval(self) -> Optional[str]: ...
    def get_status(self) -> Optional[str]: ...
    def get_type(self) -> str: ...
    def get_access(self) -> Optional[str]: ...
    def get_max_access(self) -> Optional[str]: ...
    def is_trap(self) -> bool: ...
    def is_root(self) -> bool: ...
    def is_resolved(self) -> bool: ...
    def get_source(self) -> Optional[str]: ...
